export type WatchFeature = {
  label: string;
  value: string;
};

export type Watch = {
  name: string;
  description: string;
  price?: string;
  images?: string[];
  features?: WatchFeature[];
  curiosity?: string;
};

export type Collection = {
  label: string;
  heroBg?: string;
  watches: Watch[];
};

/* Images */
import noveltiousWatch from '../../public/categories/category_NOVELTIES.jpg'
import historiadotWatch from '../../public/categories/category_HISTORIADOR.jpg'
import hemiwayWatch from '../../public/categories/category_HEMINGWAY.jpg'
import primeraWatch from '../../public/categories/category_PrimeraDama.jpg'
import robustoWatch from '../../public/categories/category_Robusto.jpg'
import prominentWatch from '../../public/categories/category_RPominente.jpg'
import esplendWatch from '../../public/categories/category_Esplendidos.jpg'
import churchillWatch from '../../public/categories/category_Churchill.jpg'
import buceadorWatch from '../../public/categories/category_Buceador.jpg'
import conographWatch from '../../public/categories/category_Chrono.jpg'
import exclusiveSelectWatch from '../../public/categories/category_Exclusive.jpg'
import allWatches from '../../public/categories/category_allwatches.jpg'




export const collectionsWatches = [
  { label: 'Novelius', bg: noveltiousWatch},
  { label: 'Historiador', bg: historiadotWatch},
  { label: 'Hemingway', bg: hemiwayWatch},
  { label: 'Primera Dama', bg: primeraWatch},
  { label: 'Robusto', bg: robustoWatch},
  { label: 'Prominente', bg: prominentWatch},
  { label: 'Esplendidos', bg: esplendWatch},
  { label: 'Churchill', bg: churchillWatch},
  { label: 'Buceador', bg: buceadorWatch},
  { label: 'Chronógrafo', bg: conographWatch},
  { label: 'Exclusive Selected Pieces', bg: exclusiveSelectWatch},
  { label: 'View All Watches', bg: allWatches},
];

export const collections: Collection[] = [
  {
    label: 'Novelius',
    heroBg: '/images/watches/novelius.jpg',
    watches: [
      {
        name: 'Gran Premio de Cuba 1957',
        price: '6.990,00',
        description: "Inspirada en las legendarias carreras callejeras de La Habana a finales de los años 50, la Trilogía Gran Premio de Cuba rinde homenaje a un capítulo único en la historia del automovilismo. Cada cronógrafo de edición limitada celebra una de las únicas tres carreras celebradas — 1957, 1958 y 1960 — mediante colores distintivos, detalles vintage de competición y artesanía mecánica suiza.  Una expresión contemporánea de velocidad, elegancia y el espíritu perdurable de La Habana.",
        images: [
          '/watches/novedades/gran-cuba-1957/3141.1GP57_Soldier-1-600x600.png',
          '/watches/novedades/gran-cuba-1957/3141.1GP57-Perspective-3-600x600.png',
          '/watches/novedades/gran-cuba-1957/3141.1GP57-Perspective-2-600x6003.png',
          '/watches/novedades/gran-cuba-1957/3141-600x600.png',
          '/watches/novedades/gran-cuba-1957/3141.1GP57_Wristshot-600x600.jpg',
          '/watches/novedades/gran-cuba-1957/1957-600x874.jpg',
        ],
        features: [
          { label: 'Funciones', value: 'Horas, minutos, segundos pequeños y cronógrafo central. Segundos pequeños a las 9 horas, contador de minutos a las 12 horas, contador de horas a las 6 horas. Visualización de fechas a las 6h' },
          { label: 'Movimientos', value: 'Valjoux 7750, automática, diámetro 30 mm, altura 7,9 mm. Reserva de marcha: 48 horas' },
          { label: 'Caso', value: 'Acero inoxidable, diámetro 41 mm, altura 15,25 mm, cristal de zafiro doble curvado con recubrimiento antirreflejante. Resistente al agua hasta 5 ATM, empujadores rectangulares de arranque/parada y reinicio, tornillado y fondo traslúdico en cristal zafiro. Fondo de caja personalizado grabado con el año del Gran Premio y con forma de volante, con un emblema CyS 2N dorado aplicado con detalles en rojo' },
          { label: 'Dial', value: "Carátula vintage marrón con encimeras color mostaza" },
          { label: 'Manos', value: "Manecillas de hora, minuto y segundos pequeños en forma de hoja, aguja de segundos cronógrafo con punta roja, manecillas de minutos y horas en forma de flecha roja" },
          { label: 'Correa', value: 'Hebilla plegable de acero inoxidable grabada con el emblema CyS' },
          { label: 'Hebilla', value: 'Correa negra de cuero mate de ternera «driving style» con costuras a juego en senapé y forro a juego' },
          { label: 'Limited Edition', value: 'LimitadaLimitado a 162 piezas. El número de piezas refleja la distancia en millas de cada carrera en circuito' },
          { label: 'Embalage', value: 'Caja de humidor estándar PE100' },
        ],
        curiosity: "¿Sabías que los colores están inspirados en el cartel original del Gran Prix?",
      },
      {
        name: 'Gran Premio de Cuba 1958',
        price: '6.990,00',
        description: " Inspirada en las legendarias carreras callejeras de La Habana a finales de los años 50, la Trilogía Gran Premio de Cuba rinde homenaje a un capítulo único en la historia del automovilismo. Cada cronógrafo de edición limitada celebra una de las únicas tres carreras celebradas — 1957, 1958 y 1960 — mediante colores distintivos, detalles vintage de competición y artesanía mecánica suiza. Una expresión contemporánea de velocidad, elegancia y el espíritu perdurable de La Habana.",
        images: [
          '/watches/novedades/gran-cuba-1958/3141.1GP58_Soldier-600x600-1.png',
          '/watches/novedades/gran-cuba-1958/3141.1GP58_Perspective-600x6002.png',
          '/watches/novedades/gran-cuba-1958/3141.1GP58_Perspective-2-600x6003.png',
          '/watches/novedades/gran-cuba-1958/3141-1-600x6004.png',
          '/watches/novedades/gran-cuba-1958/3141.1GP58_Wristshot-600x6005.jpg',
          '/watches/novedades/gran-cuba-1958/GP58-600x9016.jpg',
        ],
        features: [
          { label: 'Funciones', value: 'Horas, minutos, segundos pequeños y cronógrafo central. Segundos pequeños a las 9 horas, contador de minutos a las 12 horas, contador de horas a las 6 horas. Visualización de fechas a las 6h' },
          { label: 'Movimientos', value: 'Valjoux 7750, automática, diámetro 30 mm, altura 7,9 mm. Reserva de marcha: 48 horas' },
          { label: 'Caso', value: 'Acero inoxidable, diámetro 41 mm, altura 15,25 mm, cristal de zafiro doble curvado con recubrimiento antirreflejante. Resistente al agua hasta 5 ATM, empujadores rectangulares de arranque/parada y reinicio, tornillado y fondo traslúdico en cristal zafiro. Fondo de caja personalizado grabado con el año del Gran Premio y con forma de volante, con un emblema CyS 2N dorado aplicado con detalles en rojo' },
          { label: 'Dial', value: 'Dial amarillo de carreras con contadores verdes' },
          { label: 'Manos', value: 'Manecillas de hora, minuto y segundos pequeños en forma de hoja, aguja de segundos cronógrafo con punta roja, manecillas de minutos y horas en forma de flecha roja' },
          { label: 'Hebilla', value: 'Hebilla plegable de acero inoxidable grabada con el emblema CyS' },
          { label: 'Correa', value: 'Correa negra de cuero mate de pantorrilla «driving style» con costuras a juego en verde y forro a juego' },
        ],
        curiosity: "¿Sabías que los colores están inspirados en el cartel original del Gran Prix?",
      },
      {
        name: 'Gran Premio de Cuba 1960',
        price: '6.990,00',
        description: "Inspirada en las legendarias carreras callejeras de La Habana a finales de los años 50, la Trilogía Gran Premio de Cuba rinde homenaje a un capítulo único en la historia del automovilismo. Cada cronógrafo de edición limitada celebra una de las únicas tres carreras celebradas — 1957, 1958 y 1960 — mediante colores distintivos, detalles vintage de competición y artesanía mecánica suiza.",
        images: [
          '/watches/novedades/gran-cuba-1960/3141.1GP60_Soldier-600x6001.png',
          '/watches/novedades/gran-cuba-1960/3141.1GP60_Perspective-1-600x6002.png',
          '/watches/novedades/gran-cuba-1960/3141-1GP60_Perspective-2-600x6003.png',
          '/watches/novedades/gran-cuba-1960/3141-1GP60_Perspective-3-2-600x6004.png',
          '/watches/novedades/gran-cuba-1960/3141.1GP60_Wristshot-600x6005.jpg',
          '/watches/novedades/gran-cuba-1960/19606.jpg',
          
        ],
        features: [
          { label: 'Funciones', value: 'Horas, minutos, segundos pequeños y cronógrafo central. Segundos pequeños a las 9 horas, contador de minutos a las 12 horas, contador de horas a las 6 horas. Visualización de fechas a las 6h' },
          { label: 'Movimientos', value: 'Valjoux 7750, automática, diámetro 30 mm, altura 7,9 mm. Reserva de marcha: 48 horas' },
          { label: 'Caso', value: 'Acero inoxidable, diámetro 41 mm, altura 15,25 mm, cristal de zafiro doble curvado con recubrimiento antirreflejante. Resistente al agua hasta 5 ATM, empujadores rectangulares de arranque/parada y reinicio, tornillado y fondo traslúdico en cristal zafiro. Fondo de caja personalizado grabado con el año del Gran Premio y con forma de volante, con un emblema CyS 2N dorado aplicado con detalles en rojo' },
          { label: 'Dial', value: 'Caráter blanco con contadores rojos contrastantes' },
          { label: 'Manos', value: 'Manecillas de hora, minuto y segundos pequeños en forma de hoja, aguja de segundos cronógrafo con punta roja, manecillas de minutos y horas en forma de flecha roja' },
          { label: 'Hebilla', value: 'Hebilla plegable de acero inoxidable grabada con el emblema CyS' },
          { label: 'Correa', value: 'Correa negra de cuero mate de pantorrilla «driving style» con costuras a juego en verde y forro a juego' },
          { label: 'Edición', value: 'LimitadaLimitado a 202 piezas. El número de piezas refleja la distancia en millas de cada carrera en circuito' },
          { label: 'Embalaje', value: 'Caja de humidor estándar PE100' },
        ],
        curiosity: "¿Sabías que los colores están inspirados en el cartel original del Gran Prix?",
      },{
        name: 'Sir Winston',
        price: '6.410,00',
        description: "El Churchill ‘Sir Winston’ rinde homenaje al ex primer ministro británico, Sir Winston Churchill. Edición limitada de 282 piezas, numeradas individualmente.",
        images: [
          '/watches/novedades/sir-winston-01/2810.1SWS-Soldier-Web-1-600x6001.png',
          '/watches/novedades/sir-winston-01/2810.1SWS-Soldier-Web_additional-bracelet-1-600x6002.png',
          '/watches/novedades/sir-winston-01/2810B-1SWB-Perspective-2-Web-min-2-600x6003.png',
          '/watches/novedades/sir-winston-01/2810B-1SWB-Perspective-1-Web-min-2-600x6004.png',
          '/watches/novedades/sir-winston-01/2810B-1SWB-Perspective-3-Web-min-5-600x6005.png',
          '/watches/novedades/sir-winston-01/2810B-1SWB-Perspective-5-Web-min-5-600x6006.png',
          '/watches/novedades/sir-winston-01/2810B-1SWB-Perspective-3bis-Web-min-1-600x6007.png',
          '/watches/novedades/sir-winston-01/historiador-tradicion-san-rafael-3-1-600x6008.png',
        ],
        features: [
          { label: 'Funciones', value: 'Horas, minutos, segundos centrales, fecha y día' },
          { label: 'Movimientos', value: 'Sellita SW240-1, 11 1/2», automática, diámetro: 29,00 mm, altura: 5,05 mm, Reserva de marcha: 38 horas, 26 rubias, 28800 A/h, peso oscilante terminado con grabado. Execution Premium (Arriba)' },
          { label: 'Caso', value: 'Laterales de acero inoxidable y titanio, diámetro 43 mm, altura 12,45 mm, cristal de zafiro doble curvado con recubrimiento antirreflectante, resistente al agua hasta 10 ATM, fondo de carcasa transparente atornillado con cristal zafiro. Placa con el nombre en el lateral y número de edición limitada' },
          { label: 'Dial', value: 'Esfera guilloché plateada ‘Clou de Paris’, índices aplicados en dorado, emblema CyS aplicado con detalles rojos' },
          { label: 'Manos', value: 'Manecillas doradas de horas, minutos y segundos, segunda con punta roja' },
          { label: 'Correa', value: 'Pulsera dorada de alto brillo de caimán de Luisiana y acero inoxidable y titanio' },
          { label: 'Hebilla', value: 'Hebilla plegable de acero inoxidable grabada con el emblema CyS' },
          { label: 'Edición', value: 'Limitada282 piezas, numeradas individualmente' },
          { label: 'Embalaje', value: 'Caja de humidor estándar con correa adicional – PE110' },
        ],
        curiosity: "El Churchill Sir Winston rinde homenaje al icónico primer ministro británico conocido por su liderazgo y resiliencia. Este distinguido reloj, limitado a 282 piezas, cuenta con dos opciones de correa: un caimán de Luisiana azul oscuro de alto brillo y una pulsera de acero inoxidable y titanio, combinando elegancia con versatilidad. Su diseño clásico refleja el legado atemporal y el espíritu duradero de Churchill.",
      },{
        name: 'Sir Winston ',
        price: '6.410,00',
        description: " 3 El Churchill ‘Sir Winston’ rinde homenaje al ex primer ministro británico, Sir Winston Churchill. Edición limitada de 282 piezas, numeradas individualmente.",
        images: [
          '/watches/novedades/sir-winston-02/2810.1SWBL-Soldier-Web-1-600x6001.png',
          '/watches/novedades/sir-winston-02/2810.1SWBL-Soldier-Web_additional-bracelet-1-600x6002.png',
          '/watches/novedades/sir-winston-02/2810B-1SWB-Perspective-2-Web-min-600x6003.png',
          '/watches/novedades/sir-winston-02/2810B-1SWB-Perspective-1-Web-min-600x6004.png',
          '/watches/novedades/sir-winston-02/2810B-1SWB-Perspective-3-Web-min-3-600x6005.png',
          '/watches/novedades/sir-winston-02/2810B-1SWB-Perspective-5-Web-min-3-600x6006.png',
          '/watches/novedades/sir-winston-02/2810B-1SWB-Perspective-3bis-Web-min-600x6007.png',
          '/watches/novedades/sir-winston-02/historiador-tradicion-san-rafael-3-1-600x6007.png',
        ],
        features: [
          { label: 'Funciones', value: 'Horas, minutos, segundos centrales, fecha y día' },
          { label: 'Movimientos', value: 'Sellita SW240-1, 11 1/2», automática, diámetro: 29,00 mm, altura: 5,05 mm, Reserva de marcha: 38 horas, 26 rubias, 28800 A/h, peso oscilante terminado con grabado. Execution Premium (Arriba)' },
          { label: 'Caso', value: 'Laterales de acero inoxidable y titanio, diámetro 43 mm, altura 12,45 mm, cristal de zafiro doble curvado con recubrimiento antirreflectante, resistente al agua hasta 10 ATM, fondo de carcasa transparente atornillado con cristal zafiro. Placa con el nombre en el lateral y número de edición limitada' },
          { label: 'Dial', value: 'Esfera guilloché negra ‘Clou de Paris’, índices aplicados en dorado, emblema CyS aplicado con detalles rojos' },
          { label: 'Manos', value: 'Manecillas doradas de horas, minutos y segundos, segunda con punta roja' },
          { label: 'Correa', value: 'Pulsera de cocodrilo de Luisiana negra mate y de acero inoxidable y titanio' },
          { label: 'Hebilla', value: 'Hebilla plegable de acero inoxidable grabada con el emblema CyS' },
          { label: 'Edición', value: 'Limitada282 piezas, numeradas individualmente' },
          { label: 'Embalaje', value: 'Caja de humidor estándar con correa adicional – PE110' },
        ],
        curiosity: "El Churchill Sir Winston rinde homenaje al icónico primer ministro británico conocido por su liderazgo y resiliencia. Este distinguido reloj, limitado a 282 piezas, cuenta con dos opciones de correa: un caimán de Luisiana azul oscuro de alto brillo y una pulsera de acero inoxidable y titanio, combinando elegancia con versatilidad. Su diseño clásico refleja el legado atemporal y el espíritu duradero de Churchill.",
      },{
        name: 'Sir Winston  ',
        price: '6.410,00',
        description: "El Churchill ‘Sir Winston’ rinde homenaje al ex primer ministro británico, Sir Winston Churchill. Edición limitada de 282 piezas, numeradas individualmente.",
        images: [
          '/watches/novedades/sir-winston-03/2810.1SWBY-Soldier-Web-1-600x6001.png',
          '/watches/novedades/sir-winston-03/2810.1SWBY-Soldier-Web_additional-bracelet-1-600x6002.png',
          '/watches/novedades/sir-winston-03/2810B-1SWB-Perspective-2-Web-min-1-600x6003.png',
          '/watches/novedades/sir-winston-03/2810B-1SWB-Perspective-1-Web-min-1-600x6004.png',
          '/watches/novedades/sir-winston-03/2810B-1SWB-Perspective-3-Web-min-4-600x6005.png',
          '/watches/novedades/sir-winston-03/2810B-1SWB-Perspective-5-Web-min-4-600x6006.png',
          '/watches/novedades/sir-winston-03/2810B-1SWBY-Perspective-5-Web-min-600x6007.png',
          '/watches/novedades/sir-winston-03/2810B-1SWBY-Perspective-3bis-Web-min-600x6008.png',
          '/watches/novedades/sir-winston-03/historiador-tradicion-san-rafael-3-1-600x6009.png',
        ],
        features: [
          { label: 'Funciones', value: 'Horas, minutos, segundos centrales, fecha y día' },
          { label: 'Movimientos', value: 'Sellita SW240-1, 11 1/2», automática, diámetro: 29,00 mm, altura: 5,05 mm, Reserva de marcha: 38 horas, 26 rubias, 28800 A/h, peso oscilante terminado con grabado. Execution Premium (Arriba)' },
          { label: 'Caso', value: 'Laterales de acero inoxidable y titanio, diámetro 43 mm, altura 12,45 mm, cristal de zafiro doble curvado con recubrimiento antirreflectante, resistente al agua hasta 10 ATM, fondo de carcasa transparente atornillado con cristal zafiro. Placa con el nombre en el lateral y número de edición limitada' },
          { label: 'Dial', value: 'Carátula guilloché burdeos ‘Clou de Paris’, índices aplicados en dorado, emblema CyS aplicado con detalles rojos' },
          { label: 'Manos', value: 'Manecillas doradas de horas, minutos y segundos, segunda con punta roja' },
          { label: 'Correa', value: 'Pulsera de cocodrilo de Luisiana mate miel y acero inoxidable y titanio' },
          { label: 'Hebilla', value: 'Hebilla plegable de acero inoxidable grabada con el emblema CyS' },
          { label: 'Edicion', value: 'Limitada282 piezas, numeradas individualmente' },
          { label: 'Embalaje', value: 'Caja de humidor estándar con correa adicional – PE110' },
        ],
        curiosity: "El Churchill Sir Winston rinde homenaje al icónico primer ministro británico conocido por su liderazgo y resiliencia. Este distinguido reloj, limitado a 282 piezas, cuenta con dos opciones de correa: un caimán de Luisiana azul oscuro de alto brillo y una pulsera de acero inoxidable y titanio, combinando elegancia con versatilidad. Su diseño clásico refleja el legado atemporal y el espíritu duradero de Churchill.",
      },
    ],
  },
  {
    label: 'Historiador',
    heroBg: '/images/watches/historiador.jpg',
    watches: [
      {
        name: 'Gran Reserva',
        price: '3.810,00',
        description: "Cuervo y Sobrinos presenta con orgullo su última creación, la colección Historiador Gran Reserva, una vibrante celebración de la doble herencia de la marca, que combina la maestría en la relojería suiza con un inconfundible carácter latino. Reserva de energía 68 horas.",
        images: [
          '/watches/historiador-cat/gran-reserva-01/3101B.1GRA-Soldier-600x6001.png',
          '/watches/historiador-cat/gran-reserva-01/3101.1GRA-Perspective-3-Web-600x6002.png',
          '/watches/historiador-cat/gran-reserva-01/3101.1GRA-Perspective-1-Web-600x6003.png',
          '/watches/historiador-cat/gran-reserva-01/3101.1GRA-Perspective-2-Web-600x6004.png',
          '/watches/historiador-cat/gran-reserva-01/3101.1GRA-Wristshot-Web-600x6005.jpg',
        ],
        features: [
          { label: 'Funciones', value: 'Horas, minutos, segundos centrales y fecha' },
          { label: 'Movimientos', value: 'La Joux-Perret G100, 11 1/2», automática, diámetro: 25,6 mm, altura: 4,45 mm, Reserva de marcha: 68 horas, 24 nabas, 28800 A/h, peso oscilante terminado con el emblema CyS aplicado' },
          { label: 'Caso', value: 'Acero inoxidable, diámetro 40 mm, altura 10,85 mm, cristal de zafiro doble curvado con recubrimiento antirreflejante, resistente al agua hasta 5 ATM, fondo de caja transparente atornillado con cristal zafiro' },
          { label: 'Dial', value: 'Guillochè antracita ahumada Sunray Dial laquerada. La fecha presenta números blancos en un disco negro. Un emblema CyS aplicado se posiciona a las 12 en punto' },
          { label: 'Manos', value: 'Manecillas de horas y minutos de losangé. Segunda mano central con punta roja' },
          { label: 'Correa', value: 'Pulsera de ternera antracita o acero inoxidable' },
          { label: 'Hebilla', value: 'Hebilla plegable de acero inoxidable grabada con el emblema CyS' },
          { label: 'Embalaje', value: 'Caja pequeña de humidor – PE211-2020' },
        ],
        curiosity: "¿Sabías que el nombre Gran Reserva refleja las excepcionales capacidades técnicas de este modelo—concretamente, su reserva de energía de 68 horas? Impulsado por el mecanismo automático La Joux-Perret G100, este reloj garantiza una autonomía impresionante, manteniendo una hora fiable incluso cuando no se lleva casi tres días sin usarlo. Con una esfera lacada guilloché y rayo sol en tonos ricos como rojo, azul, verde o antracita, combina hábilmente la precisión suiza con el espíritu latino.",
      },{
        name: 'Gran Reserva ',
        price: '3.810,00',
        description: "Cuervo y Sobrinos presenta con orgullo su última creación, la colección Historiador Gran Reserva, una vibrante celebración de la doble herencia de la marca, que combina la maestría en la relojería suiza con un inconfundible carácter latino. Reserva de energía 68 horas.",
        images: [
          '/watches/historiador-cat/gran-reserva-02/3101.1GRA-Soldier-600x6001.png',
          '/watches/historiador-cat/gran-reserva-02/3101.1GRA-Perspective-3-Web-600x6002.png',
          '/watches/historiador-cat/gran-reserva-02/3101.1GRA-Perspective-1-Web-600x6003.png',
          '/watches/historiador-cat/gran-reserva-02/3101.1GRA-Perspective-2-Web-600x6004.png',
          '/watches/historiador-cat/gran-reserva-02/3101.1GRA-Wristshot-Web-600x6005.jpg',
        ],
        features: [
          { label: 'Funciones', value: 'Horas, minutos, segundos centrales y fecha' },
          { label: 'Movimientos', value: 'La Joux-Perret G100, 11 1/2», automática, diámetro: 25,6 mm, altura: 4,45 mm, Reserva de marcha: 68 horas, 24 nabas, 28800 A/h, peso oscilante terminado con el emblema CyS aplicado' },
          { label: 'Caso', value: 'Acero inoxidable, diámetro 40 mm, altura 10,85 mm, cristal de zafiro doble curvado con recubrimiento antirreflejante, resistente al agua hasta 5 ATM, fondo de caja transparente atornillado con cristal zafiro' },
          { label: 'Dial', value: 'Guillochè antracita ahumada Sunray Dial laquerada. La fecha presenta números blancos en un disco negro. Un emblema CyS aplicado se posiciona a las 12 en punto' },
          { label: 'Manos', value: 'Manecillas de horas y minutos de losangé. Segunda mano central con punta roja' },
          { label: 'Correa', value: 'Pulsera de ternera antracita o acero inoxidable' },
          { label: 'Hebilla', value: 'Hebilla plegable de acero inoxidable grabada con el emblema CyS' },
          { label: 'Embalaje', value: 'Caja pequeña de humidor – PE211-2020' },
        ],
        curiosity: "¿Sabías que el nombre Gran Reserva refleja las excepcionales capacidades técnicas de este modelo—concretamente, su reserva de energía de 68 horas? Impulsado por el mecanismo automático La Joux-Perret G100, este reloj garantiza una autonomía impresionante, manteniendo una hora fiable incluso cuando no se lleva casi tres días sin usarlo. Con una esfera lacada guilloché y rayo sol en tonos ricos como rojo, azul, verde o antracita, combina hábilmente la precisión suiza con el espíritu latino.",
      },{
        name: 'Gran Reserva  ',
        price: '3.810,00',
        description: "Cuervo y Sobrinos presenta con orgullo su última creación, la colección Historiador Gran Reserva, una vibrante celebración de la doble herencia de la marca, que combina la maestría en la relojería suiza con un inconfundible carácter latino. Reserva de energía 68 horas.",
        images: [
          '/watches/historiador-cat/gran-reserva-03/3101B.1GRB-Soldier-Web-600x6001.png',
          '/watches/historiador-cat/gran-reserva-03/3101.1GRB-Perspective-4-Web-600x6002.png',
          '/watches/historiador-cat/gran-reserva-03/3101.1GRB-Perspective-3-Web-600x6003.png',
          '/watches/historiador-cat/gran-reserva-03/3101.1GRB-Perspective-2-Web-600x6004.png',
          '/watches/historiador-cat/gran-reserva-03/3101.1GRB-600x6005.jpg',
        ],
        features: [
          { label: 'Funciones', value: 'Horas, minutos, segundos centrales y fecha' },
          { label: 'Movimientos', value: 'La Joux-Perret G100, 11 1/2», automática, diámetro: 25,6 mm, altura: 4,45 mm, Reserva de marcha: 68 horas, 24 nabas, 28800 A/h, peso oscilante terminado con el emblema CyS aplicado' },
          { label: 'Caso', value: 'Acero inoxidable, diámetro 40 mm, altura 10,85 mm, cristal de zafiro doble curvado con recubrimiento antirreflejante, resistente al agua hasta 5 ATM, fondo de caja transparente atornillado con cristal zafiro' },
          { label: 'Dial', value: 'Esfera sunray ahumada en azul guilloché laquerada. La fecha presenta números blancos en un disco negro. Un emblema CyS aplicado se posiciona a las 12 en punto' },
          { label: 'Manos', value: 'Manecillas de horas y minutos de losangé. Central rojo-segunda mano con punta' },
          { label: 'Correa', value: 'Pulsera azul marino de cuero de becerro o acero inoxidable' },
          { label: 'Hebilla', value: 'Hebilla plegable de acero inoxidable grabada con el emblema CyS' },
          { label: 'Embalaje', value: 'Caja pequeña de humidor – PE211-2020' },
        ],
        curiosity: "¿Sabías que el nombre Gran Reserva refleja las excepcionales capacidades técnicas de este modelo—concretamente, su reserva de energía de 68 horas? Impulsado por el mecanismo automático La Joux-Perret G100, este reloj garantiza una autonomía impresionante, manteniendo una hora fiable incluso cuando no se lleva casi tres días sin usarlo. Con una esfera lacada guilloché y rayo sol en tonos ricos como rojo, azul, verde o antracita, combina hábilmente la precisión suiza con el espíritu latino.",
      },{
        name: 'Gran Reserva   ',
        price: '3.810,00',
        description: "Cuervo y Sobrinos presenta con orgullo su última creación, la colección Historiador Gran Reserva, una vibrante celebración de la doble herencia de la marca, que combina la maestría en la relojería suiza con un inconfundible carácter latino. Reserva de energía 68 horas.",
        images: [
          '/watches/historiador-cat/gran-reserva-04/3101.1GRB-Soldier-Web-600x6001.png',
          '/watches/historiador-cat/gran-reserva-04/3101.1GRB-Perspective-4-Web-600x6002.png',
          '/watches/historiador-cat/gran-reserva-04/3101.1GRB-Perspective-3-Web-600x6003.png',
          '/watches/historiador-cat/gran-reserva-04/3101.1GRB-Perspective-2-Web-600x6004.png',
          '/watches/historiador-cat/gran-reserva-04/3101.1GRB-600x6005.jpg',
        ],
        features: [
          { label: 'Funciones', value: 'Horas, minutos, segundos centrales y fecha' },
          { label: 'Movimientos', value: 'La Joux-Perret G100, 11 1/2», automática, diámetro: 25,6 mm, altura: 4,45 mm, Reserva de marcha: 68 horas, 24 nabas, 28800 A/h, peso oscilante terminado con el emblema CyS aplicado' },
          { label: 'Caso', value: 'Acero inoxidable, diámetro 40 mm, altura 10,85 mm, cristal de zafiro doble curvado con recubrimiento antirreflejante, resistente al agua hasta 5 ATM, fondo de caja transparente atornillado con cristal zafiro' },
          { label: 'Dial', value: 'Esfera sunray ahumada en azul guilloché laquerada. La fecha presenta números blancos en un disco negro. Un emblema CyS aplicado se posiciona a las 12 en punto' },
          { label: 'Manos', value: 'Manecillas de horas y minutos de losangé. Central rojo-segunda mano con punta' },
          { label: 'Correa', value: 'Pulsera azul marino de cuero de becerro o acero inoxidable' },
          { label: 'Hebilla', value: 'Hebilla plegable de acero inoxidable grabada con el emblema CyS' },
          { label: 'Embalaje', value: 'Caja pequeña de humidor – PE211-2020' },
        ],
        curiosity: "¿Sabías que el nombre Gran Reserva refleja las excepcionales capacidades técnicas de este modelo—concretamente, su reserva de energía de 68 horas? Impulsado por el mecanismo automático La Joux-Perret G100, este reloj garantiza una autonomía impresionante, manteniendo una hora fiable incluso cuando no se lleva casi tres días sin usarlo. Con una esfera lacada guilloché y rayo sol en tonos ricos como rojo, azul, verde o antracita, combina hábilmente la precisión suiza con el espíritu latino.",
      },{
        name: 'Gran Reserva    ',
        price: '3.810,00',
        description: "Cuervo y Sobrinos presenta con orgullo su última creación, la colección Historiador Gran Reserva, una vibrante celebración de la doble herencia de la marca, que combina la maestría en la relojería suiza con un inconfundible carácter latino. Reserva de energía 68 horas.",
        images: [
          '/watches/historiador-cat/gran-reserva-05/3101B.1GRR-Soldier-Web-600x6001.png',
          '/watches/historiador-cat/gran-reserva-05/3101.1GRR-Perspective-3-Web-600x6002.png',
          '/watches/historiador-cat/gran-reserva-05/3101.1GRR-Perspective-1-Web-600x6003.png',
          '/watches/historiador-cat/gran-reserva-05/3101.1GRR-Perspective-2-Web-600x6004.png',
          '/watches/historiador-cat/gran-reserva-05/3101.1GRR-Perspective-4-Web-600x6005.png',
          '/watches/historiador-cat/gran-reserva-05/3101.1GRR-Wristshot-Web-600x6006.jpg',
        ],
        features: [
          { label: 'Funciones', value: 'Horas, minutos, segundos centrales y fecha' },
          { label: 'Movimientos', value: 'La Joux-Perret G100, 11 1/2», automática, diámetro: 25,6 mm, altura: 4,45 mm, Reserva de marcha: 68 horas, 24 nabas, 28800 A/h, peso oscilante terminado con el emblema CyS aplicado' },
          { label: 'Caso', value: 'Acero inoxidable, diámetro 40 mm, altura 10,85 mm, cristal de zafiro doble curvado con recubrimiento antirreflejante, resistente al agua hasta 5 ATM, fondo de caja transparente atornillado con cristal zafiro' },
          { label: 'Dial', value: 'Esfera sunray ahumada en rojo guilloché laca. La fecha presenta números blancos en un disco negro. Un emblema CyS aplicado se posiciona a las 12 en punto' },
          { label: 'Manos', value: 'Manecillas de horas y minutos de losangé. Segunda mano central con punta roja' },
          { label: 'Correa', value: 'Pulsera de cuero de becerro burdeos o acero inoxidable' },
          { label: 'Hebilla', value: 'Hebilla plegable de acero inoxidable grabada con el emblema CyS' },
          { label: 'Embalaje', value: 'Caja pequeña de humidor – PE211-2020' },
        ],
        curiosity: "¿Sabías que el nombre Gran Reserva refleja las excepcionales capacidades técnicas de este modelo—concretamente, su reserva de energía de 68 horas? Impulsado por el mecanismo automático La Joux-Perret G100, este reloj garantiza una autonomía impresionante, manteniendo una hora fiable incluso cuando no se lleva casi tres días sin usarlo. Con una esfera lacada guilloché y rayo sol en tonos ricos como rojo, azul, verde o antracita, combina hábilmente la precisión suiza con el espíritu latino.",
      },{
        name: 'Gran Reserva     ',
        price: '3.810,00',
        description: "Cuervo y Sobrinos presenta con orgullo su última creación, la colección Historiador Gran Reserva, una vibrante celebración de la doble herencia de la marca, que combina la maestría en la relojería suiza con un inconfundible carácter latino. Reserva de energía 68 horas.",
        images: [
          '/watches/historiador-cat/gran-reserva-06/3101.1GRR-Soldier-Web-600x6001.png',
          '/watches/historiador-cat/gran-reserva-06/3101.1GRR-Perspective-3-Web-600x6002.png',
          '/watches/historiador-cat/gran-reserva-06/3101.1GRR-Perspective-1-Web-600x6003.png',
          '/watches/historiador-cat/gran-reserva-06/3101.1GRR-Perspective-2-Web-600x6004.png',
          '/watches/historiador-cat/gran-reserva-06/3101.1GRR-Perspective-4-Web-600x6005.png',
          '/watches/historiador-cat/gran-reserva-06/3101.1GRR-Wristshot-Web-600x6006.jpg',
        ],
        features: [
          { label: 'Funciones', value: 'Horas, minutos, segundos centrales y fecha' },
          { label: 'Movimientos', value: 'La Joux-Perret G100, 11 1/2», automática, diámetro: 25,6 mm, altura: 4,45 mm, Reserva de marcha: 68 horas, 24 nabas, 28800 A/h, peso oscilante terminado con el emblema CyS aplicado' },
          { label: 'Caso', value: 'Acero inoxidable, diámetro 40 mm, altura 10,85 mm, cristal de zafiro doble curvado con recubrimiento antirreflejante, resistente al agua hasta 5 ATM, fondo de caja transparente atornillado con cristal zafiro' },
          { label: 'Dial', value: 'Esfera sunray ahumada en rojo guilloché laca. La fecha presenta números blancos en un disco negro. Un emblema CyS aplicado se posiciona a las 12 en punto' },
          { label: 'Manos', value: 'Manecillas de horas y minutos de losangé. Segunda mano central con punta roja' },
          { label: 'Correa', value: 'Pulsera de cuero de becerro burdeos o acero inoxidable' },
          { label: 'Hebilla', value: 'Hebilla plegable de acero inoxidable grabada con el emblema CyS' },
          { label: 'Embalaje', value: 'Caja pequeña de humidor – PE211-2020' },
        ],
        curiosity: "¿Sabías que el nombre Gran Reserva refleja las excepcionales capacidades técnicas de este modelo—concretamente, su reserva de energía de 68 horas? Impulsado por el mecanismo automático La Joux-Perret G100, este reloj garantiza una autonomía impresionante, manteniendo una hora fiable incluso cuando no se lleva casi tres días sin usarlo. Con una esfera lacada guilloché y rayo sol en tonos ricos como rojo, azul, verde o antracita, combina hábilmente la precisión suiza con el espíritu latino.",
      },{
        name: 'Gran Reserva      ',
        price: '3.810,00',
        description: "Cuervo y Sobrinos presenta con orgullo su última creación, la colección Historiador Gran Reserva, una vibrante celebración de la doble herencia de la marca, que combina la maestría en la relojería suiza con un inconfundible carácter latino. Reserva de energía 68 horas.",
        images: [
          '/watches/historiador-cat/gran-reserva-07/3101.1GRG-Soldier-600x6001.png',
          '/watches/historiador-cat/gran-reserva-07/3101.1GRG-Perspective-3-Web-600x6002.png',
          '/watches/historiador-cat/gran-reserva-07/3101.1GRG-Perspective-1-Web-600x6003.png',
          '/watches/historiador-cat/gran-reserva-07/3101.1GRG-Perspective-2-Web-600x6004.png',
          '/watches/historiador-cat/gran-reserva-07/3101.1GRG-600x6005.jpg',
        ],
        features: [
          { label: 'Funciones', value: 'Horas, minutos, segundos centrales y fecha' },
          { label: 'Movimientos', value: 'La Joux-Perret G100, 11 1/2», automática, diámetro: 25,6 mm, altura: 4,45 mm, Reserva de marcha: 68 horas, 24 nabas, 28800 A/h, peso oscilante terminado con el emblema CyS aplicado' },
          { label: 'Caso', value: 'Acero inoxidable, diámetro 40 mm, altura 10,85 mm, cristal de zafiro doble curvado con recubrimiento antirreflejante, resistente al agua hasta 5 ATM, fondo de caja transparente atornillado con cristal zafiro' },
          { label: 'Dial', value: 'Esfera Sunray ahumada verde guilloché laca. La fecha presenta números blancos en un disco negro. Un emblema CyS aplicado se posiciona a las 12 en punto' },
          { label: 'Manos', value: 'Manecillas de horas y minutos de losangé. Segunda mano central con punta roja' },
          { label: 'Correa', value: 'Hebilla plegable de acero inoxidable grabada con el emblema CyS' },
          { label: 'Hebilla', value: 'Pulsera verde de cuero de becerro o acero inoxidable' },
          { label: 'Embalaje', value: 'Caja pequeña de humidor – PE211-2020' },
        ],
        curiosity: "¿Sabías que el nombre Gran Reserva refleja las excepcionales capacidades técnicas de este modelo—concretamente, su reserva de energía de 68 horas? Impulsado por el mecanismo automático La Joux-Perret G100, este reloj garantiza una autonomía impresionante, manteniendo una hora fiable incluso cuando no se lleva casi tres días sin usarlo. Con una esfera lacada guilloché y rayo sol en tonos ricos como rojo, azul, verde o antracita, combina hábilmente la precisión suiza con el espíritu latino.",
      },{
        name: 'Gran Reserva       ',
        price: '3.810,00',
        description: "Cuervo y Sobrinos presenta con orgullo su última creación, la colección Historiador Gran Reserva, una vibrante celebración de la doble herencia de la marca, que combina la maestría en la relojería suiza con un inconfundible carácter latino. Reserva de energía 68 horas.",
        images: [
          '/watches/historiador-cat/gran-reserva-08/3101B.1GRG-Soldier-600x6001.png',
          '/watches/historiador-cat/gran-reserva-08/3101.1GRG-Perspective-3-Web-600x6002.png',
          '/watches/historiador-cat/gran-reserva-08/3101.1GRG-Perspective-1-Web-600x6003.png',
          '/watches/historiador-cat/gran-reserva-08/3101.1GRG-Perspective-2-Web-600x6004.png',
          '/watches/historiador-cat/gran-reserva-08/3101.1GRG-600x6005.jpg',
        ],
        features: [
          { label: 'Funciones', value: 'Horas, minutos, segundos centrales y fecha' },
          { label: 'Movimientos', value: 'La Joux-Perret G100, 11 1/2», automática, diámetro: 25,6 mm, altura: 4,45 mm, Reserva de marcha: 68 horas, 24 nabas, 28800 A/h, peso oscilante terminado con el emblema CyS aplicado' },
          { label: 'Caso', value: 'Acero inoxidable, diámetro 40 mm, altura 10,85 mm, cristal de zafiro doble curvado con recubrimiento antirreflejante, resistente al agua hasta 5 ATM, fondo de caja transparente atornillado con cristal zafiro' },
          { label: 'Dial', value: 'Esfera Sunray ahumada verde guilloché laca. La fecha presenta números blancos en un disco negro. Un emblema CyS aplicado se posiciona a las 12 en punto' },
          { label: 'Manos', value: 'Manecillas de horas y minutos de losangé. Segunda mano central con punta roja' },
          { label: 'Correa', value: 'Pulsera verde de cuero de becerro o acero inoxidable' },
          { label: 'Hebilla', value: 'Hebilla plegable de acero inoxidable grabada con el emblema CyS' },
          { label: 'Embalaje', value: 'Caja pequeña de humidor – PE211-2020' },
        ],
        curiosity: "¿Sabías que el nombre Gran Reserva refleja las excepcionales capacidades técnicas de este modelo—concretamente, su reserva de energía de 68 horas? Impulsado por el mecanismo automático La Joux-Perret G100, este reloj garantiza una autonomía impresionante, manteniendo una hora fiable incluso cuando no se lleva casi tres días sin usarlo. Con una esfera lacada guilloché y rayo sol en tonos ricos como rojo, azul, verde o antracita, combina hábilmente la precisión suiza con el espíritu latino.",
      },{
        name: 'Asturias Pequeños Segundos',
        price: '4.220,00',
        description: "Cuervo y Sobrinos fue fundada en 1882 por Cuervo y sus sobrinos. Este grupo de empresarios notables y orfebres altamente cualificados procedía de Asturias, una región del noroeste de España. El Historiador Asturias honra a aquellos valientes emigrantes que, en el siglo XIX, navegaron hacia América en busca de la fortuna. Cuba resultó ser una elección popular para los intrépidos asturianos, ansiosos por descubrir un nuevo mundo y construir una vida mejor.",
        images: [
          '/watches/historiador-cat/asturias-pequeños-segundos/3102B.1HLE-Soldier-Web-600x6001.png',
          '/watches/historiador-cat/asturias-pequeños-segundos/3102B.1LE_Back_Web-600x6002.png',
          '/watches/historiador-cat/asturias-pequeños-segundos/3102B.1LE-Life3-Web-600x6003.png',
          '/watches/historiador-cat/asturias-pequeños-segundos/3102B.1LE-Life2-Web-600x6004.png',
          '/watches/historiador-cat/asturias-pequeños-segundos/3102B.1LE-Side1-Web-600x6005.png',
          '/watches/historiador-cat/asturias-pequeños-segundos/3102B.1LE-Life-Web-600x6006.png',
          '/watches/historiador-cat/asturias-pequeños-segundos/3102B.1LE-Side-Web-600x6007.png',
        ],
        features: [
          { label: 'Funciones', value: 'Horas, minutos, segundos pequeños' },
          { label: 'Movimientos', value: 'Sellita SW 261, 11 1/2», automática, diámetro: 25,6 mm, altura: 5,6 mm, reserva de marcha 38 horas, 31 piedras, 28800 A/h, peso oscilante terminado con grabado' },
          { label: 'Caso', value: 'Acero inoxidable, diámetro 40 mm, altura 10,95 mm, cristal de zafiro doble curvado con recubrimiento antirreflejante, resistente al agua hasta 5 ATM, fondo de caja transparente atornillado con cristal de zafiro' },
          { label: 'Dial', value: 'Crema, apliqué índices con tratamiento de rodio, apliqué el emblema CyS a las 12 horas' },
          { label: 'Manos', value: 'Manecillas de las horas y los minutos de losangé de plata con manecilla de segundos pequeños en forma de bastón' },
          { label: 'Correa', value: 'Pulsera de cocodrilo de Louisiana o acero inoxidable marrón chocolate mate' },
          { label: 'Hebilla', value: 'Hebilla plegable de acero inoxidable grabada con el emblema CyS' },
          { label: 'Edicion', value: 'Limitada82 piezas, numeradas individualmente' },
          { label: 'Embalaje', value: 'Caja pequeña de humidor – PE211-2020' },
        ],
        curiosity: "¿Sabías que el Asturias Pequeños Segundos recibe su nombre por su elegante subdial de segundos pequeños a las 6 en punto? Este modelo refinado, limitado a solo 82 piezas, alberga un mecanismo automático con una reserva de marcha de 38 horas, visible a través de su fondo de caja zafiro — un verdadero homenaje al lujo discreto y la rareza.",
      },{
        name: 'Asturias Pequeños Segundos ',
        price: '4.220,00',
        description: "Cuervo y Sobrinos fue fundada en 1882 por Cuervo y sus sobrinos. Este grupo de empresarios notables y orfebres altamente cualificados procedía de Asturias, una región del noroeste de España. El Historiador Asturias honra a aquellos valientes emigrantes que, en el siglo XIX, navegaron hacia América en busca de la fortuna. Cuba resultó ser una elección popular para los intrépidos asturianos, ansiosos por descubrir un nuevo mundo y construir una vida mejor.",
        images: [
          '/watches/historiador-cat/asturias-pequeños-segundos-02/3102.1HLE-Soldier-Web-600x6001.png',
          '/watches/historiador-cat/asturias-pequeños-segundos-02/3102B.1LE_Back_Web-600x6002.png',
          '/watches/historiador-cat/asturias-pequeños-segundos-02/3102B.1LE-Life3-Web-600x6003.png',
          '/watches/historiador-cat/asturias-pequeños-segundos-02/3102B.1LE-Life2-Web-600x6004.png',
          '/watches/historiador-cat/asturias-pequeños-segundos-02/3102B.1LE-Side1-Web-600x6005.png',
          '/watches/historiador-cat/asturias-pequeños-segundos-02/3102B.1LE-Life-Web-600x6006.png',
          '/watches/historiador-cat/asturias-pequeños-segundos-02/3102B.1LE-Side-Web-600x6007.png',
        ],
        features: [
          { label: 'Funciones', value: 'Horas, minutos, segundos pequeños' },
          { label: 'Movimientos', value: 'Sellita SW 261, 11 1/2», automática, diámetro: 25,6 mm, altura: 5,6 mm, reserva de marcha 38 horas, 31 piedras, 28800 A/h, peso oscilante terminado con grabado' },
          { label: 'Caso', value: 'Acero inoxidable, diámetro 40 mm, altura 10,95 mm, cristal de zafiro doble curvado con recubrimiento antirreflejante, resistente al agua hasta 5 ATM, fondo de caja transparente atornillado con cristal de zafiro' },
          { label: 'Dial', value: 'Crema, apliqué índices con tratamiento de rodio, apliqué el emblema CyS a las 12 horas' },
          { label: 'Manos', value: 'Manecillas de las horas y los minutos de losangé de plata con manecilla de segundos pequeños en forma de bastón' },
          { label: 'Correa', value: 'Pulsera de cocodrilo de Louisiana o acero inoxidable marrón chocolate mate' },
          { label: 'Hebilla', value: 'Hebilla plegable de acero inoxidable grabada con el emblema CyS' },
          { label: 'Edicion', value: 'Limitada82 piezas, numeradas individualmente' },
          { label: 'Embalaje', value: 'Caja pequeña de humidor – PE211-2020' },
        ],
        curiosity: "¿Sabías que el Asturias Pequeños Segundos recibe su nombre por su elegante subdial de segundos pequeños a las 6 en punto? Este modelo refinado, limitado a solo 82 piezas, alberga un mecanismo automático con una reserva de marcha de 38 horas, visible a través de su fondo de caja zafiro — un verdadero homenaje al lujo discreto y la rareza.",
      },
    ],
  },
  {
    label: 'Hemingway',
    heroBg: '/images/watches/hemingway.jpg',
    watches: [
      {
        name: 'Hemingway Icónico',
        price: '4.080,00',
        description: "Cuervo y Sobrinos rinde homenaje a su cliente de toda la vida y fiel Ernest Hemingway, célebre escritor y auténtica leyenda del siglo XX, con el lanzamiento de una nueva colección dedicada íntegramente al escritor.",
        images: [
          '/watches/hemingway/hemingway-iconico/3190.1ICC-Soldier-Web-600x6001.png',
          '/watches/hemingway/hemingway-iconico/3190.1ICC-Perspective-4-Web-600x6002.png',
          '/watches/hemingway/hemingway-iconico/3190.1ICC-Perspective-3-Web-600x6004.png',
          '/watches/hemingway/hemingway-iconico/3190.1ICC-Perspective-4-Web-600x6002.png',
          '/watches/hemingway/hemingway-iconico/3190.1ICC-Buckle-Web-600x6005.png',
          '/watches/hemingway/hemingway-iconico/hemingway-5-600x6006.png',
          '/watches/hemingway/hemingway-iconico/hemingway-6-600x6007.png',
        ],
        features: [
          { label: 'Funciones', value: 'Horas, minutos, fecha de puntero con corrector rápido' },
          { label: 'Movimientos', value: 'Sellita 221-1, 11 1/2», automática, diámetro: 26 mm, altura: 5,05 mm, Reserva de marcha: 38 horas, 26 rubios, 28800 A/h, peso oscilante terminado con grabado' },
          { label: 'Caso', value: 'Acero inoxidable, diámetro 40 mm, altura 12,05 mm, cristal de zafiro doble curvado con recubrimiento antirreflectante, resistente al agua hasta 10 ATM, corona atornillada. Logotipo grabado de Hemingway en la parte trasera de la caja y placa de edición limitada en la caja lateral' },
          { label: 'Dial', value: 'Esfera crema, recubrimiento de índices Super-LumiNova® y emblema CyS aplicado' },
          { label: 'Manos', value: 'Manecillas plateadas de las horas y los minutos con Super-Luminova®, manecilla de segundos de acero azul y puntero plateado con forma de cola de pez' },
          { label: 'Correa', value: 'Correa de cuero marrón claro' },
          { label: 'Hebilla', value: 'Hebilla plegable de acero inoxidable grabada con el emblema CyS' },
          { label: 'Edicion', value: 'Limitada882 piezas' },
          { label: 'Embalaje', value: 'PE 107 – Caja de libros Hemingway' },
        ],
        curiosity: "¿Sabías que el Hemingway Icónico es una edición limitada de solo 882 piezas? Impulsado por el motor automático Sellita SW221-1, ofrece una reserva de marcha de 38 horas. El modelo presenta una fecha con puntero con una punta azul o roja, y la manecilla de los segundos termina en una cola de pez de marlín, rindiendo homenaje al amor de Hemingway por la pesca. Dentro de la corona encontrarás la cita: «Para escribir sobre la vida, primero debes vivirla», grabada tanto en inglés como en español.",
      },{
        name: 'Hemingway Icónico ',
        price: '4.080,00',
        description: "Cuervo y Sobrinos rinde homenaje a su cliente de toda la vida y fiel Ernest Hemingway, célebre escritor y auténtica leyenda del siglo XX, con el lanzamiento de una nueva colección dedicada íntegramente al escritor.",
        images: [
          '/watches/hemingway/hemingway-iconico-02/3190.1ICB-600x6001.png',
          '/watches/hemingway/hemingway-iconico-02/hemingway-3-600x6002.png',
          '/watches/hemingway/hemingway-iconico-02/hemingway-1-600x6003.png',
          '/watches/hemingway/hemingway-iconico-02/hemingway-2-600x6004.png',
          '/watches/hemingway/hemingway-iconico-02/hemingway-4-600x6005.png',
          '/watches/hemingway/hemingway-iconico-02/hemingway-5-600x6006.png',
          '/watches/hemingway/hemingway-iconico-02/hemingway-6-600x6007.png',
        ],
        features: [
          { label: 'Funciones', value: 'Horas, minutos, fecha de puntero con corrector rápido' },
          { label: 'Movimientos', value: 'Sellita 221-1, 11 1/2», automática, diámetro: 26 mm, altura: 5,05 mm, Reserva de marcha: 38 horas, 26 rubios, 28800 A/h, peso oscilante terminado con grabado' },
          { label: 'Caso', value: 'Caráter marrón, índices Super-LumiNova® recubiertos, emblema CyS aplicado' },
          { label: 'Dial', value: 'Acero inoxidable, diámetro 40 mm, altura 12,05 mm, cristal de zafiro doble curvado con recubrimiento antirreflectante, resistente al agua hasta 10 ATM, corona atornillada. Logotipo grabado de Hemingway en la parte trasera de la caja y placa de edición limitada en la caja lateral' },
          { label: 'Manos', value: 'Manecillas plateadas de las horas y los minutos con Super-Luminova®, manecilla de segundos de acero plateada y puntero rojo con forma de cola de pez' },
          { label: 'Correa', value: 'Correa de cuero marrón oscuro' },
          { label: 'Hebilla', value: 'Hebilla plegable de acero inoxidable grabada con el emblema CyS' },
          { label: 'Edicion', value: 'Limitada882 piezas' },
          { label: 'Embalaje', value: 'PE 107 – Caja de libros Hemingway' },
        ],
        curiosity: "¿Sabías que el Hemingway Icónico es una edición limitada de solo 882 piezas? Impulsado por el motor automático Sellita SW221-1, ofrece una reserva de marcha de 38 horas. El modelo presenta una fecha con puntero con una punta azul o roja, y la manecilla de los segundos termina en una cola de pez de marlín, rindiendo homenaje al amor de Hemingway por la pesca. Dentro de la corona encontrarás la cita: «Para escribir sobre la vida, primero debes vivirla», grabada tanto en inglés como en español.",
      },{
        name: 'Hemingway Icónico ‘The Fisherman’',
        price: '5.100,00',
        description: "Cuervo y Sobrinos rinde homenaje a su cliente de toda la vida y fiel Ernest Hemingway, célebre escritor y auténtica leyenda del siglo XX, con el lanzamiento de una nueva colección dedicada íntegramente al escritor.",
        images: [
          '/watches/hemingway/hemingway-fisherman/3192B.1B_soldier-600x6001.png',
          '/watches/hemingway/hemingway-fisherman/3192B.1B-Perspective-4-Web-600x6002.png',
          '/watches/hemingway/hemingway-fisherman/3192.1B-Soldier_Cordura-starp-600x6003.png',
          '/watches/hemingway/hemingway-fisherman/3192B.1B-Perspective-2-Web-600x6004.png',
          '/watches/hemingway/hemingway-fisherman/3192B.1B-Buckle-Web-600x6005.png',
          '/watches/hemingway/hemingway-fisherman/3192B.1B-Perspective-3-Web-600x6006.png',
          '/watches/hemingway/hemingway-fisherman/3192.1B-wristshot-600x4507.jpg',
          '/watches/hemingway/hemingway-fisherman/Hemingway-book-box-closed-600x6008.png',
        ],
        features: [
          { label: 'Funciones', value: 'Horas, minutos, segundos centrales, fecha y GMT' },
          { label: 'Movimientos', value: 'Soprod C125, automático, diámetro: 26,2 mm, altura: 4,1 mm, Reserva de marcha: 42 horas, 26 piedras, 28800 A/h, peso oscilante terminado con grabado' },
          { label: 'Caso', value: 'Acero inoxidable, diámetro 40 mm, altura 12,15 mm, cristal de zafiro doble curvado con recubrimiento antirreflejante, resistente al agua hasta 10 ATM, corona atornillada. Parte trasera de la caja abierta con el logo de Hemingway Hemingway en el peso oscilante, y la placa de edición limitada en la caja lateral' },
          { label: 'Dial', value: 'Caráter azul océano, índices Super-LumiNova® recubiertos, emblema CyS aplicado' },
          { label: 'Manos', value: 'Manecillas plateadas de horas y minutos con Super-Luminova®, manecilla blanca de los segundos y aguja azul GMT' },
          { label: 'Correa', value: 'Hebilla plegable cuadrada de acero inoxidable grabada con el emblema CyS' },
          { label: 'Hebilla', value: 'Pulsera de acero inoxidable y correa textil azul gris de cordura' },
          { label: 'Edicion', value: 'Limitada288 piezas' },
          { label: 'Embalaje', value: 'PE107 – Caja de relojes Hemingway' },
        ],
        curiosity: "¿Sabías que ‘El pescador’ de Hemingway es una edición limitada de solo 288 piezas? Cuenta con el mecanismo automático Soprod C125 con una reserva de marcha de 42 horas. La esfera azul océano rinde homenaje a la novela corta de Hemingway El viejo y el mar, escrita en Cayo Blanco. Los elementos de diseño incluyen una escala GMT de 24 horas en el bisel, una ventana de fechas y una cita dentro de la corona. El reloj se presenta en un embalaje especial que recuerda a un libro clásico, añadiendo una capa extra de sofisticación y encanto literario a la colección.",
      },
    ],
  },
  {
    label: 'Primera Dama',
    heroBg: '/images/watches/primera-dama.jpg',
    watches: [
      {
        name: 'Diamante Rosa',
        price: '9,800',
        description: "Set with a crown of rose-cut diamonds, Diamante Rosa is the definitive expression of feminine strength and Havana's timeless glamour.",
        images: ['/images/watches/primera-dama/diamante-rosa-1.png'],
        features: [
          { label: 'Funciones', value: 'Hours, minutes' },
          { label: 'Movimientos', value: 'Quartz, Swiss Made' },
          { label: 'Caso', value: 'Stainless steel with rose gold PVD coating, diameter 34 mm, set with 60 rose-cut diamonds' },
          { label: 'Dial', value: 'Mother-of-pearl with diamond hour markers' },
          { label: 'Correa', value: 'Pink satin strap' },
          { label: 'Hebilla', value: 'Rose gold PVD pin buckle' },
          { label: 'Embalage', value: 'Premium Humidor Box – PE 200' },
        ],
        curiosity: "Each diamond on the Diamante Rosa bezel is individually set by hand, a process requiring over six hours of work by a master setter in the Maison's Geneva atelier.",
      },
      {
        name: 'Esmeralda',
        price: '8,400',
        description: "A deep green dial framed by a diamond-set bezel evokes the lush gardens of Old Havana in a piece made for the discerning collector.",
        images: ['/images/watches/primera-dama/esmeralda-1.png'],
        features: [
          { label: 'Funciones', value: 'Hours, minutes' },
          { label: 'Movimientos', value: 'Quartz, Swiss Made' },
          { label: 'Caso', value: 'Stainless steel, diameter 34 mm, diamond-set bezel' },
          { label: 'Dial', value: 'Deep forest green lacquered dial' },
          { label: 'Correa', value: 'Green alligator leather' },
          { label: 'Hebilla', value: 'Stainless Steel pin buckle' },
          { label: 'Embalage', value: 'Premium Humidor Box – PE 200' },
        ],
        curiosity: "The Esmeralda dial is lacquered in three successive layers, each cured for 24 hours, to achieve the characteristic depth of its forest green color.",
      },
    ],
  },
  {
    label: 'Robarto',
    heroBg: '/images/watches/robarto.jpg',
    watches: [
      {
        name: 'Robusto',
        price: '5,400',
        description: "Built for the bold, Robusto features a 44mm case in brushed stainless steel with a skeletonized automatic movement.",
        images: ['/images/watches/robarto/robusto-1.png'],
        features: [
          { label: 'Funciones', value: 'Hours, minutes, seconds — skeletonized display' },
          { label: 'Movimientos', value: 'Automatic skeleton, Power Reserve: 46 hours' },
          { label: 'Caso', value: 'Brushed stainless steel, diameter 44 mm, water resistant to 10 ATM' },
          { label: 'Dial', value: 'Open skeleton with black bridges' },
          { label: 'Correa', value: 'Black rubber strap' },
          { label: 'Hebilla', value: 'Stainless Steel pin buckle' },
          { label: 'Embalage', value: 'Standard Humidor Box – PE 100' },
        ],
        curiosity: "The Robusto movement is skeletonized by hand using a micro-abrasive process that removes material to within 0.2mm of structural tolerances.",
      },
      {
        name: 'Fuerte',
        price: '4,900',
        description: "With 200m water resistance and a unidirectional rotating bezel, Fuerte transitions effortlessly from the ocean to the boardroom.",
        images: ['/images/watches/robarto/fuerte-1.png'],
        features: [
          { label: 'Funciones', value: 'Hours, minutes, seconds, date' },
          { label: 'Movimientos', value: 'Automatic, Power Reserve: 44 hours' },
          { label: 'Caso', value: 'Stainless steel, diameter 42 mm, water resistant to 200m / 20 ATM' },
          { label: 'Bezel', value: 'Unidirectional rotating bezel with ceramic insert' },
          { label: 'Dial', value: 'Blue sunburst with luminous applied indices' },
          { label: 'Bracelet', value: 'Stainless steel oyster-style bracelet' },
          { label: 'Clasp', value: 'Wet-suit extension folding clasp' },
          { label: 'Embalage', value: 'Standard Humidor Box – PE 100' },
        ],
        curiosity: "The Fuerte's ceramic bezel insert is sintered at over 1,400°C, making it virtually scratchproof and colorfast for the lifetime of the watch.",
      },
    ],
  },
  {
    label: 'Prominente',
    heroBg: '/images/watches/prominente.jpg',
    watches: [
      {
        name: 'Gran Reserva',
        price: '12,500',
        description: "A grand complication for the grand occasion, Gran Reserva features a perpetual calendar, moon phase, and 72-hour power reserve.",
        images: ['/images/watches/prominente/gran-reserva-1.png'],
        features: [
          { label: 'Funciones', value: 'Hours, minutes, perpetual calendar, moon phase, power reserve indicator' },
          { label: 'Movimientos', value: 'Automatic, Power Reserve: 72 hours, 35 jewels' },
          { label: 'Caso', value: '18K rose gold, diameter 42 mm, sapphire case back, water resistant to 3 ATM' },
          { label: 'Dial', value: 'Silver guilloché with blue moon phase aperture' },
          { label: 'Correa', value: 'Dark cognac alligator leather' },
          { label: 'Hebilla', value: '18K rose gold pin buckle' },
          { label: 'Embalage', value: 'Premium Humidor Box – PE 200' },
        ],
        curiosity: "The Gran Reserva perpetual calendar requires no manual correction until the year 2100, when a single adjustment for the secular leap year will be needed.",
      },
      {
        name: 'Senador',
        price: '7,200',
        description: "Senador's slim profile conceals an ultra-thin movement, making it the ideal dress watch for moments that demand understated authority.",
        images: ['/images/watches/prominente/senador-1.png'],
        features: [
          { label: 'Funciones', value: 'Hours, minutes' },
          { label: 'Movimientos', value: 'Ultra-thin automatic, Height: 2.4 mm, Power Reserve: 38 hours' },
          { label: 'Caso', value: '18K white gold, diameter 38 mm, height 6.9 mm, water resistant to 3 ATM' },
          { label: 'Dial', value: 'White lacquered with thin gold applied baton indices' },
          { label: 'Correa', value: 'Black alligator leather' },
          { label: 'Hebilla', value: '18K white gold pin buckle' },
          { label: 'Embalage', value: 'Premium Humidor Box – PE 200' },
        ],
        curiosity: "At 6.9mm total height, the Senador slides effortlessly under a formal shirt cuff — a constraint the movement engineers treated as a design challenge rather than a limitation.",
      },
    ],
  },
  {
    label: 'Esplendidos',
    heroBg: '/images/watches/esplendidos.jpg',
    watches: [
      {
        name: 'Magnífico',
        price: '5,600',
        description: "A celebration of Havana's golden era, Magnífico dresses a classic round case with a champagne dial and applied gold indices.",
        images: ['/images/watches/esplendidos/magnifico-1.png'],
        features: [
          { label: 'Funciones', value: 'Hours, minutes, central seconds, date' },
          { label: 'Movimientos', value: 'Automatic, Power Reserve: 42 hours' },
          { label: 'Caso', value: 'Yellow gold PVD stainless steel, diameter 40 mm, water resistant to 5 ATM' },
          { label: 'Dial', value: 'Champagne sunburst with applied gold baton indices' },
          { label: 'Correa', value: 'Havana brown alligator leather' },
          { label: 'Hebilla', value: 'Gold PVD folding buckle' },
          { label: 'Embalage', value: 'Standard Humidor Box – PE 100' },
        ],
        curiosity: "The champagne dial of the Magnífico is lacquered using a formula originally developed for the restoration of Art Deco interiors in 1940s Havana.",
      },
      {
        name: 'Dorado',
        price: '18,000',
        description: "An 18K gold case and a hand-engraved dial make Dorado the crown jewel of the Esplendidos collection.",
        images: ['/images/watches/esplendidos/dorado-1.png'],
        features: [
          { label: 'Funciones', value: 'Hours, minutes, central seconds' },
          { label: 'Movimientos', value: 'Automatic, Power Reserve: 44 hours, COSC Certified' },
          { label: 'Caso', value: '18K yellow gold, diameter 40 mm, sapphire case back, water resistant to 3 ATM' },
          { label: 'Dial', value: '18K gold hand-engraved dial, unique floral motif' },
          { label: 'Correa', value: 'Black alligator leather' },
          { label: 'Hebilla', value: '18K gold folding buckle' },
          { label: 'Embalage', value: 'Premium Humidor Box – PE 200' },
        ],
        curiosity: "No two Dorado dials are identical — each engraving is executed freehand by a single artisan, making every piece a unique work of applied art.",
      },
    ],
  },
  {
    label: 'Churchill',
    heroBg: '/images/watches/churchill.jpg',
    watches: [
      {
        name: 'Maduro',
        price: '5,200',
        description: "As distinguished as its namesake, Maduro pairs a rich brown dial with a hand-stitched tobacco leather strap and a rose gold case.",
        images: ['/images/watches/churchill/maduro-1.png'],
        features: [
          { label: 'Funciones', value: 'Hours, minutes, central seconds, date' },
          { label: 'Movimientos', value: 'Automatic, Power Reserve: 42 hours' },
          { label: 'Caso', value: 'Rose gold PVD stainless steel, diameter 41 mm, water resistant to 5 ATM' },
          { label: 'Dial', value: 'Rich brown with applied rose gold indices' },
          { label: 'Correa', value: 'Hand-stitched tobacco leather' },
          { label: 'Hebilla', value: 'Rose gold PVD pin buckle' },
          { label: 'Embalage', value: 'Standard Humidor Box – PE 100' },
        ],
        curiosity: "The tobacco leather for the Maduro strap is tanned using a traditional Cuban process that takes 14 weeks to complete.",
      },
      {
        name: 'Claro',
        price: '4,800',
        description: "A lighter take on the Churchill spirit, Claro features a pale cream dial and a polished silver case for moments of refined ease.",
        images: ['/images/watches/churchill/claro-1.png'],
        features: [
          { label: 'Funciones', value: 'Hours, minutes, central seconds' },
          { label: 'Movimientos', value: 'Automatic, Power Reserve: 40 hours' },
          { label: 'Caso', value: 'Polished stainless steel, diameter 39 mm, water resistant to 5 ATM' },
          { label: 'Dial', value: 'Pale cream lacquered with slim silver indices' },
          { label: 'Correa', value: 'Light tan leather strap' },
          { label: 'Hebilla', value: 'Stainless Steel pin buckle' },
          { label: 'Embalage', value: 'Standard Humidor Box – PE 100' },
        ],
        curiosity: "The Claro's cream lacquer is applied in five successive coats, each polished between applications, to achieve its characteristic warm tone.",
      },
    ],
  },
  {
    label: 'Buceador',
    heroBg: '/images/watches/buceador.jpg',
    watches: [
      {
        name: 'Profundo',
        price: '6,100',
        description: "Rated to 300m, Profundo is the technical flagship of the Buceador line — a tool watch without compromise, refined for the surface world.",
        images: ['/images/watches/buceador/profundo-1.png'],
        features: [
          { label: 'Funciones', value: 'Hours, minutes, seconds, date' },
          { label: 'Movimientos', value: 'Automatic, Power Reserve: 48 hours, anti-magnetic' },
          { label: 'Caso', value: 'Stainless steel, diameter 43 mm, water resistant to 300m / 30 ATM, screw-down crown' },
          { label: 'Bezel', value: 'Unidirectional rotating bezel with ceramic insert, 60-minute graduation' },
          { label: 'Dial', value: 'Black with luminescent applied indices and hands' },
          { label: 'Bracelet', value: 'Stainless steel with wet-suit extension' },
          { label: 'Embalage', value: 'Standard Humidor Box – PE 100' },
        ],
        curiosity: "The Profundo case is pressure-tested individually at 330m before leaving the factory, 10% beyond its rated depth to ensure a safety margin in real-world use.",
      },
      {
        name: 'Arrecife',
        price: '5,800',
        description: "Arrecife's vivid blue dial evokes the coral reefs of the Caribbean, wrapped in a lightweight titanium case built for deep exploration.",
        images: ['/images/watches/buceador/arrecife-1.png'],
        features: [
          { label: 'Funciones', value: 'Hours, minutes, seconds, date' },
          { label: 'Movimientos', value: 'Automatic, Power Reserve: 48 hours' },
          { label: 'Caso', value: 'Grade 5 titanium, diameter 42 mm, water resistant to 200m / 20 ATM' },
          { label: 'Bezel', value: 'Unidirectional rotating ceramic bezel' },
          { label: 'Dial', value: 'Vivid blue gradient with coral-red second hand' },
          { label: 'Correa', value: 'Blue rubber strap with titanium buckle' },
          { label: 'Embalage', value: 'Standard Humidor Box – PE 100' },
        ],
        curiosity: "Grade 5 titanium is 40% lighter than stainless steel yet equally strong, allowing the Arrecife to be worn for extended dives without fatigue.",
      },
    ],
  },
  {
    label: 'Chronógrafo',
    heroBg: '/images/watches/chronografo.jpg',
    watches: [
      {
        name: 'Veloce',
        price: '6,800',
        description: "A column-wheel flyback chronograph with a tachymeter bezel, Veloce was born on the racetrack and refined in the ateliers of Havana.",
        images: ['/images/watches/chronografo/veloce-1.png'],
        features: [
          { label: 'Funciones', value: 'Hours, minutes, small seconds, flyback chronograph, tachymeter' },
          { label: 'Movimientos', value: 'Automatic column-wheel flyback, Power Reserve: 48 hours' },
          { label: 'Caso', value: 'Stainless steel, diameter 43 mm, water resistant to 10 ATM' },
          { label: 'Bezel', value: 'Fixed tachymeter bezel' },
          { label: 'Dial', value: 'Racing black with contrasting white registers' },
          { label: 'Correa', value: 'Racing perforated leather strap' },
          { label: 'Hebilla', value: 'Stainless Steel pin buckle' },
          { label: 'Embalage', value: 'Standard Humidor Box – PE 100' },
        ],
        curiosity: "A flyback chronograph can be reset and restarted with a single push of the pusher, a function originally developed for timing successive laps at motor racing circuits.",
      },
      {
        name: 'Piloto',
        price: '6,200',
        description: "Oversized pushers, a dual-register dial, and a matte black case make Piloto the definitive aviator-inspired chronograph.",
        images: ['/images/watches/chronografo/piloto-1.png'],
        features: [
          { label: 'Funciones', value: 'Hours, minutes, small seconds at 9, 30-minute counter at 3, chronograph' },
          { label: 'Movimientos', value: 'Automatic, column-wheel, Power Reserve: 46 hours' },
          { label: 'Caso', value: 'Matte black PVD stainless steel, diameter 44 mm, water resistant to 10 ATM' },
          { label: 'Dial', value: 'Matte black with high-contrast white registers and luminous hands' },
          { label: 'Correa', value: 'Black canvas pilot strap' },
          { label: 'Hebilla', value: 'Black PVD pin buckle' },
          { label: 'Embalage', value: 'Standard Humidor Box – PE 100' },
        ],
        curiosity: "The Piloto's oversized crown and pushers are designed to be operated while wearing flight gloves — a specification borrowed directly from 1960s aviation-grade instrument watches.",
      },
    ],
  },
  {
    label: 'Exclusive Selected Pieces',
    heroBg: '/images/watches/exclusive.jpg',
    watches: [
      {
        name: 'Havana Exclusivo',
        price: '32,000',
        description: "A one-of-a-kind expression produced in a single numbered edition, featuring a meteorite dial and a hand-engraved platinum case.",
        images: ['/images/watches/exclusive/havana-exclusivo-1.png'],
        features: [
          { label: 'Funciones', value: 'Hours, minutes, central seconds, power reserve' },
          { label: 'Movimientos', value: 'Automatic, Power Reserve: 72 hours, COSC Certified, individually numbered' },
          { label: 'Caso', value: 'Platinum 950, diameter 41 mm, sapphire case back, water resistant to 3 ATM' },
          { label: 'Dial', value: 'Gibeon meteorite, unique pattern, hand-engraved CyS emblem' },
          { label: 'Correa', value: 'Black crocodile leather' },
          { label: 'Hebilla', value: 'Platinum 950 folding buckle' },
          { label: 'Limited Edition', value: '1 piece, uniquely numbered' },
          { label: 'Embalage', value: 'Premium Humidor Box – PE 500' },
        ],
        curiosity: "The Gibeon meteorite used for the dial fell to Earth approximately 4 billion years ago and was discovered in Namibia in 1836 — making the dial older than our solar system's planets.",
      },
      {
        name: 'Age For Glory',
        price: '14,500',
        description: "Designed to commemorate the pursuit of greatness, Age For Glory features an anniversary complication and an engraved sapphire case back.",
        images: ['/images/watches/exclusive/age-for-glory-1.png'],
        features: [
          { label: 'Funciones', value: 'Hours, minutes, seconds, annual calendar, power reserve indicator' },
          { label: 'Movimientos', value: 'Automatic, annual calendar complication, Power Reserve: 60 hours' },
          { label: 'Caso', value: '18K rose gold, diameter 42 mm, engraved sapphire case back, water resistant to 3 ATM' },
          { label: 'Dial', value: 'Deep blue with rose gold applied indices and anniversary engraving' },
          { label: 'Correa', value: 'Navy blue alligator leather' },
          { label: 'Hebilla', value: '18K rose gold folding buckle' },
          { label: 'Limited Edition', value: '50 pieces, individually numbered' },
          { label: 'Embalage', value: 'Premium Humidor Box – PE 300' },
        ],
        curiosity: "An annual calendar requires only one manual correction per year — on March 1st, when it cannot distinguish the short month of February from longer months.",
      },
    ],
  },
  {
    label: 'View All Watches',
    heroBg: '/images/watches/all.jpg',
    watches: [],
  },
];

/* 
Creation new watch

{
        name: '',
        price: '',
        description: "",
        images: [
          '',
        ],
        features: [
          { label: 'Funciones', value: '' },
          { label: 'Movimientos', value: '' },
          { label: 'Caso', value: '' },
          { label: 'Dial', value: '' },
          { label: 'Manos', value: '' },
          { label: 'Correa', value: '' },
          { label: 'Hebilla', value: '' },
          { label: 'Edicion', value: '' },
          { label: 'Embalaje', value: '' },
        ],
        curiosity: "",
      },
*/